// MODULE
import Link from 'next/link.js';

// COMPONENT
import  Footer  from '../app/components/Footer.jsx';
import  Header  from '../app/components/Header.jsx';
import WhatsAppButton from '../app/components/WhatsAppButton.jsx';

// STYLING
import './globals.css'
import '../app/styles/image.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';




export const metadata = {
  title: 'DREWHITE',
  description: 'Generated by TheGoodJon',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        < WhatsAppButton />
        <Footer />
        </body>
    </html>
  )
}
