
// import Header from './components/Header'
// import Footer from './components/Footer'
import './globals.css'
import './globals.module.css'



export const metadata = {
  title: 'DREWHITE',
  description: 'Generated by TheGoodJon',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
        </body>
    </html>
  )
}
